trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@3
  inputs:
    mavenPomFile: - task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    pmdRunAnalysis: true
    findBugsRunAnalysis: true 

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: myweb'
  inputs:
    targetPath: '$(Pipeline.Workspace)' 
    artifactName: "myweb.war"
  condition: succeeded()

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: current
    artifact: 'myweb.war'


